
service: sls-kinesis-test

provider:
  name: aws
  runtime: nodejs4.3
  region: ap-northeast-1
  stage: dev
  cfLogs: true
  profile: default
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ec2:CreateNetworkInterface
        - ec2:DeleteNetworkInterface
        - ec2:DescribeNetworkInterfaces
      Resource: "*"

package:
  exclude:
    - .DS_Store
    - .gitignore
    - .npmignore
    - .git/**
    - .idea/**
    - node_modules/aws-sdk
    - node_modules/serverless-offline
    - data/**
    - package.json
    - README.md
    - secret.txt


functions:
  getStream:
    handler: handler.kinesisHandler
    events:
      - stream:
          type: kinesis
          # arn: 
          #   Fn::GetAtt:
          #     - lambda_kinesis_test
          #     - Arn
          arn: arn:aws:kinesis:ap-northeast-1:042083552617:stream/lambda_kinesis_test
    vpc:
      securityGroupIds:
        - sg-ea98b18d
      subnetIds:
        - subnet-b138a8e9